### ISSUE TITLE
Add ESP32 Support

### ISSUE THREAD

**Issue by nitrotm** [raburton/rboot#26]
As the ESP32 is available ~~for some time~~ now, that would be great to see how to port rboot to that chip if possible. My first impression is that it's pretty close to ESP8266 in terms of architecture and the RTOS sdk seems very similar in features / boot image format.
But there are two cores and new features so it might be just an impression.
Did someone try rboot on ESP32 already?

**Comment by nitrotm** [comment]
Just saw espressif last sdk (esp-idf). It seems much more open than the ones for esp8266 (the bootloader source is available), so might not be so important to have rboot on the esp32 after all...

**Comment by raburton** [comment]
Agreed, I don't think there is the same need for rBoot on esp32 as there was on the original.
