### ISSUE TITLE
don't use rtc mem data

### ISSUE THREAD

**Issue by riban-bw** [raburton/rboot#3]
After rBoot runs and loads a ROM, the ESP8266 prints "don't use rtc mem data" to its serial port. A quick search of Google suggests this may be a warning that RTC memory has been corrupted but I haven't investigated far.

**Comment by raburton** [comment]
That's common on boot if rtc hasn't been initialised (e.g. after hard reset, power one, etc). rBoot doesn't touch the rtc.
