### ISSUE TITLE
rboot example with big flash support

### ISSUE THREAD

**Issue by fvpalha** [raburton/rboot#32]
Hello.

A example with big flash support will be usefull.

Thank you.

**Comment by daffysub** [comment]
Hello Raburton

I have provide a very good work, but I didn't find how we can specify the flash size when we have higher size than 8Mbit.
Could you give me a hint, please?

Thank you in advance.

**Comment by raburton** [comment]
I'm sorry but I no longer have a development setup for esp8266 so I can't whip up a sample, but the documentation is pretty thorough and others projects using rBoot (such as Sming) have examples using big flash support that you could take a look at.
