### ISSUE TITLE
Why rboot need up to addr 0x2000?

### ISSUE THREAD

**Issue by daffysub** [raburton/rboot#34]
Hello Raburton,

Why have you specify that rboot is placed between addr 0x00000 and 0x2000? 
Ok for addr 0x0000 but the bootloader and the structure fo rboot config don't really need of all that?

**Comment by raburton** [comment]
rBoot needs about half a sector. The config needs very little space, but
needs to be in a separate sector so when it is rewritten there is no risk
of losing the bootloader itself.

**Comment by daffysub** [comment]
OK Thank you for your response.
