### ISSUE TITLE
Bootloader restore

### ISSUE THREAD

**Issue by dunk8888** [raburton/rboot#35]
Hi,just want to ask a question,sorry first of all for posting hear,I want to restore the bootloader on my esp8266,it seems that its corrupt or something like that,i dont realy understand the esp at all,ime used to 328p and attiny85 etc,now i understand that the bootloader sits in the flash unit that resides next to the esp chip, am i right? also i cant find a bootloader bin thats allready compiled,also if the bootloader is broken how do i fix it,dont i need a bootloader on the esp to add a bootloader? i mean how do i get it into the bootloader mode if its broke,or does the flash need to be taken of and flashed using another method? also have you a compiled bootloader i can try? any will do i just want to try save my nodemcu.Thanks

**Comment by raburton** [comment]
The esp8266 has a built in boot loader in its internal rom, you do not need anything else to flash a normal program like nodemcu.
