### ISSUE TITLE
666k firmware flash

### ISSUE THREAD

**Issue by kiralikbeyin** [raburton/rboot#55]
My firmware is big so i added (https://github.com/SuperHouse/esp-open-rtos/issues/674)
````
    *sdklib*:*(.irom.* .irom.*.* .irom0.*)
````

I came here from https://github.com/SuperHouse/esp-open-rtos/issues/498
SuperHouse rboot is not working for a simple blink firmware... 

I found another lib which flashes blink.bin but blink.bin size is 250k https://github.com/apiel/aboot/issues/2

I am lost now, is it possible to make an 666k bin flash?

**Comment by raburton** [comment]
rBoot is a bootloader, it does not affect the running of your code. In fact from the other issue you linked it does not look like you can get your code to compile and link, so you haven't even got to using rBoot yet.
